export { default as Numbar } from './Numbar/Numbar'
export { default as Map } from './Map/Map'
export { default as Bar } from './Bar/Bar'
export { default as Doughnut } from './Doughnut/Doughnut'
export { default as Doughnut2 } from './Doughnut2/Doughnut2'
export { GetSize } from './GetSize/GetSize'
export { GetData } from './GetData/GetData'
export { default as Header } from './Header/Header'